### ISSUE TITLE
Multiple credential stores

### ISSUE THREAD

**Issue by asilvas** [asilvas/node-image-steam#14]
How best to handle multi-credential storage drivers. One possibility is to support domain-to-credential mapping. Support would be on a per-credential basis. There's always the possibility of custom storage solutions to map header values, or parts of a path name, but ideally we want to support the common use cases.

Suggestions appreciated.

**Comment by asilvas** [comment]
Done

**Comment by SharadKumar** [comment]
Hi mate - this doesn't seem to work!
I am trying to run this with for two domains on same port. So I passed options as:

```
{
...
domain: {
  'domain1.com:3000': {storage: {}},
  'domain2.com:3000': {storage: {}}
}
storage: {}
...
}
```

https://github.com/asilvas/node-image-steam/blob/15ed3e0838685482332777af96f3bf0c0e1c15b0/lib/storage/index.js#L117-L120

**Comment by SharadKumar** [comment]
If I don't see `storage` at root level, domain ones do not get picked and by default storage becomes `fs` obviously as default.

**Comment by asilvas** [comment]
Yep this is per design, you'll always want a root `storage` as your default. Your `domain` settings will merge onto those defaults. https://github.com/asilvas/node-image-steam/blob/15ed3e0838685482332777af96f3bf0c0e1c15b0/lib/storage/index.js#L17

**Comment by asilvas** [comment]
@SharadKumar I see how the docs were misleading. Updated to clarify. Thanks!
