### ISSUE TITLE
google cloud storage

### ISSUE THREAD

**Issue by stellanhaglund** [asilvas/node-image-steam#19]
Any plans for google cloud storage?

**Comment by asilvas** [comment]
@stellanhaglund no plans, but welcome a PR! Shouldn't be hard, there's a good reference here: https://github.com/asilvas/node-image-steam/tree/master/lib/storage/s3

**Comment by stellanhaglund** [comment]
Okay I will look into it, i'm having troubles starting the server though i
get

Error: VipsOperation: class "webpsave_buffer" not found

2015-09-15 15:21 GMT+02:00 Aaron <notifications@github.com>:

**Comment by asilvas** [comment]
WebP for whatever reason isn't always built by default in libvips it seems. I'm guessing you're using OSX?

Try http://sharp.dimens.io/en/stable/install/

**Comment by stellanhaglund** [comment]
Yes thats the one i followed

tisdag 15 september 2015 skrev Aaron <notifications@github.com>:

**Comment by asilvas** [comment]
@stellanhaglund any luck getting webp working with libvips? If not you might try posting here: https://github.com/lovell/sharp/issues

**Comment by asilvas** [comment]
Closing. Re-open if someone wants to submit a PR
