### ISSUE TITLE
Support use like sendFile

### ISSUE THREAD

**Issue by wmertens** [asilvas/node-image-steam#39]
I would like to use this in an application where file access is restricted, and to that end there is an authorization layer that then uses sendFile to pass the file to the user.

So basically, given a file (or a stream?) and options, convert, cache, and return a file.

Is that possible to do with the plugins system?

**Comment by asilvas** [comment]
Yes it's possible. Feel free to create your own storage plugin. If it's something you feel may be useful to a wide audience, submit as a PR and it may be bundled in.

Examples:
* [S3](https://github.com/asilvas/node-image-steam/blob/master/lib/storage/s3/index.js)
* [File System](https://github.com/asilvas/node-image-steam/blob/master/lib/storage/fs/index.js)
* [HTTP (Read-only)](https://github.com/asilvas/node-image-steam/blob/master/lib/storage/http/index.js) - Read-only storage plugins are useful for fetching original assets, but can't be used for caching (unless extended with basic auth or some other form of auth)

Once you create your plugin, just set `storage = { driverPath: "./my-new-storage-plugin" }`.

**Comment by asilvas** [comment]
Closing. Let me know if more questions
