### ISSUE TITLE
Option to disable cache

### ISSUE THREAD

**Issue by Loyz07** [asilvas/node-image-steam#53]
Hello,

At first, thanks for the job. 

To continue with a little issue. With sharp we can disable caching with option  cache: false but in image-steam we can't because options we pass are always merged with defaults one in an empty object that is different from 'false'.

Is there a way to disable it ?

Thanks.

**Comment by asilvas** [comment]
Good catch, thanks for the report.

Fix published in `0.53.3`.

**Comment by asilvas** [comment]
Example:
```
{
  processor: {
    sharp: {
      cache: false
    }
  }
}
```

**Comment by Loyz07** [comment]
Amazing reactivity !

Thanks.
