### ISSUE TITLE
How to upload with optimization

### ISSUE THREAD

**Issue by jialbanc** [asilvas/node-image-steam#58]
I want to know how the images uploading process work, as it is described in your docs. Thanks for your help.

**Comment by asilvas** [comment]
Hi @jialbanc -- images are not uploaded to isteam. Instead isteam acts as a reverse proxy, pulling the assets from the origin storage you've configured. The cached assets that isteam generates to avoid unnecessarily reprocessing images is stored in the cache you've configured; or if none specified, will use the root `storage` where the original assets live. In other words, you upload images to your storage the way you already do today.

**Comment by jialbanc** [comment]
Thanks a lot for the fast reply :)
