### ISSUE TITLE
Latency at displaying an upload image the first time

### ISSUE THREAD

**Issue by jialbanc** [asilvas/node-image-steam#59]
Good night, i made a service uploading images on the same folder that is used by your image steam web server to process images, after the upload is complete i make a request of that image, but it fails by 
 been displayed on a tag "img" as it is showed on the picture above. 
This only happens when the picture is heavy and big, so it's probably a latency when your web server tries to generate the caching.
![image](https://user-images.githubusercontent.com/2524546/38279189-c2ff0940-3764-11e8-8533-0812a1e709e9.png)
There is a way to force that cache generation inmediatly after uploading or another way.

I will aprecciate your help.

**Comment by jialbanc** [comment]
Thanks for your response.
The logs shows me this error after requesting the image as you see in the image above.
![image](https://user-images.githubusercontent.com/2524546/38316043-68fcb6f0-37ef-11e8-9e42-4f4ddc619862.png)
These are the details of the image I'm trying to upload.
![image](https://user-images.githubusercontent.com/2524546/38316167-b6ff38a0-37ef-11e8-834e-cfbe3d0a4fe0.png)
I already try changing the config options, the cpu have 4 cores. Above are my setup options:

![image](https://user-images.githubusercontent.com/2524546/38318526-2289e278-37f5-11e8-9dba-2fba7aa13d6f.png)

![image](https://user-images.githubusercontent.com/2524546/38318514-1997af1a-37f5-11e8-928a-20ed1d46686a.png)

Thanks for your help.

**Comment by jialbanc** [comment]
Hi @asilvas again, i would appreciate if you could take a look of my project [https://github.com/jialbanc/image-test](url), I already debug it and couldn't find the exact line of the error. Thanks for your help

**Comment by asilvas** [comment]
Your project works fine. You're probably trying to access root (`localhost:13337/`), but instead you want to access assets in your files folder. If `files/image.jpg` exists, you'll be able to access it via `localhost:13337/image.jpg`, which in turn means you can do image operations ala `localhost:13337/image.jpg/:/rs=w:200`
