### ISSUE TITLE
Is there any benefit to adding a cdn in front of image-steam?

### ISSUE THREAD

**Issue by dottodot** [asilvas/node-image-steam#67]
Just wondering if in your experience there is much benefit to having a cdn in front of image-steam?

**Comment by asilvas** [comment]
Highly dependent on your usage patterns and architecture. If assets are accessed frequent enough to resolve at the CDN, then most certainly a benefit. Even if your CDN cache hit rates aren't ideal (< 50%), there are other benefits such as H2, and edge routes to origin are often more optimal than client to origin direct. It's rarely a bad idea to use a CDN. With that said, image-steam can be used with a diverse range of architectures, including replication across several DC's (via AWS S3 for instance), providing a CDN-like experience. But in general, CDN is going to bring the bigger bang for the buck.

**Comment by asilvas** [comment]
For a reference point, we use isteam across a few regions (routed via geo-DNS, much like route53) w/o replication, fronted by CDN. Each region is cached by a persistent (S3 compatible) store with 5-day TTL's on objects. Our median response times are sub 40ms, which is pretty good for images. Our 99th is much higher, mostly in part to having to fetch from origin which can be in a different region. Our cache hit rates on CDN are fairly low, but still beneficial.

**Comment by dottodot** [comment]
@asilvas Nice one, thanks for taking the time to answer.
