### ISSUE TITLE
integrate ovh cloud storage

### ISSUE THREAD

**Issue by musicformellons** [asilvas/node-image-steam#68]
This looks really cool. Was wondering whether it would work with OVH cloud api (based on openstack): https://api.ovh.com/console/#/cloud

Could this work with the [http client](https://github.com/asilvas/node-image-steam#storage-client---http)? Or would I need to make a custom client?

**Comment by asilvas** [comment]
Howdy,

Not sure. Give it a shot. Should be pretty quick to verify. Anything that can be mapped or emulated to work with raw node.js http requests should work. Let us know how it goes!

**Comment by musicformellons** [comment]
Ok. I might start with AWS and then maybe try OVH later...
