### ISSUE TITLE
Add image padding

### ISSUE THREAD

**Issue by dottodot** [asilvas/node-image-steam#71]
Is there a way to add padding to an image. I've tried everything I can think of but with no luck.

An example of what I'm trying to achieve is I have an original image that is is 1200px by 800px and I'd like to be able to convert it to a square i.e 1200px by 1200px and fill the excess with a colour.

**Comment by asilvas** [comment]
This behavior is not yet supported in isteam. Happy to take PR's! Should be possible: https://sharp.pixelplumbing.com/en/stable/api-resize/

**Comment by dottodot** [comment]
I'm assuming it would be the extend option. Happy to look at doing a PR but might just need a little guidance to get started. Would extend to to be a separate option so that you'd have something like

```
rs=w:800/ex=t:10,b:10,l:10,r:10
```

**Comment by asilvas** [comment]
The interface for background is out of date for background, so it'll need to be pulled into this function and the resize function.

Examples:

```
rs=w:800,bg:#000000
exd=t:10,b:10,l:10,r:10,bg:#000000
```

Notice the only change in signature I made was to make the new function `exd` to avoid ambiguity with extract.

The existing `background` function will need to away. So the changes will impact 3 functions in total, `rs` (update to support `bg`), `exd` (new), and `bg` (remove).

**Comment by dottodot** [comment]
OK thanks I will have a go, only problem I'm have is the xxhash dependency doesn't seem to want to install, have you had an issue with it before?

**Comment by asilvas** [comment]
I have not, but native deps have always been a pain getting the proper environment setup that plays nice with all native deps. https://github.com/mscdex/node-xxhash/issues?utf8=%E2%9C%93&q=is%3Aissue

**Comment by dottodot** [comment]
Using node 8 seemed to do the trick it doesn't like 10 or 11

**Comment by dottodot** [comment]
Sorry one last thing, as there isn't currently any support for nested objects would something like below be acceptable for the background color config

```
    exd: {
      name: 'extend',
      t: 'top',
      b: 'bottom',
      l: 'left',
      r: 'right',
      'bg-r': 'red',
      'bg-g': 'green',
      'bg-b': 'blue',
      'bg-a': 'alpha',
      'bg-h': 'hex'
    }
```

**Comment by asilvas** [comment]
Sounds good, though I'd rename `bg-h` as just `bg`.

**Comment by asilvas** [comment]
Getting close I believe, just having issues with sharp respecting the `background`. It's always using black regardless of what we pass in.

**Comment by asilvas** [comment]
Release `v0.49` addresses this.
