### ISSUE TITLE
Unable to parse color from object

### ISSUE THREAD

**Issue by dottodot** [asilvas/node-image-steam#72]
When trying to use the Background option i.e `bg=#ffffff` or `bg=r:255,g:255,b:255` I get an error of

```
Unable to parse color from object: {"r":255,"g":255,"b":255,"a":1}
```

**Comment by asilvas** [comment]
Thanks for the report. I'll try to get to it in the next week. Unless of course you want to submit PR! ;-)

**Comment by asilvas** [comment]
Release `v0.49` addresses this.
