### ISSUE TITLE
SVG Images unable to process

### ISSUE THREAD

**Issue by patelmayankce** [asilvas/node-image-steam#80]
Can anyone help how to fix the below error?

I am running service in the Linux environment and getting below error.

`
mage-stream  | ERR: 2019-10-01T13:24:44.008Z GET /fileadmin/user_upload/svg/ecm-2.svg/:/rs=w:100,h:29/qt=q:80
`
`
image-stream  | Error: svgload_buffer: SVG rendering failed
`

It works well in windows system.

**Comment by asilvas** [comment]
Would be helpful to reproduce: https://github.com/lovell/sharp#examples

If you can create a gist using `sharp` that reproduces the issue we can post it there.

**Comment by patelmayankce** [comment]
@asilvas, I tried to process through this example repo. https://github.com/nikwen/sharp-demo/tree/svg-resize-height-width

and it works well in Linux env. So is there any configuration am I missing which should I change in node-image-tream which increase SVG buffer size or something?

**Comment by asilvas** [comment]
Sorry for the delay just running behind. I won't be able to look at this until tomorrow at the earliest. If you can help debug that would be helpful. Pr's welcome!

**Comment by asilvas** [comment]
@patelmayankce this might have to do with the encoding. Which storage driver are you using?

**Comment by patelmayankce** [comment]
@asilvas I am using http as a storage driver.

**Comment by asilvas** [comment]
Unable to repro. Will re-open if PR.
