### ISSUE TITLE
cache=false not working? (fs driver)

### ISSUE THREAD

**Issue by endymonium** [asilvas/node-image-steam#82]
Hi,

I saw there is a ?cache=false flag mentioned in the docs, but if I set it, the image is still being read from the cache:

`P2220008.JPG/:/rs=w:4?cache=false`

I would like to query image steam to check if the original source is still there.

Jan

**Comment by asilvas** [comment]
Hey there @endymonium. It's a bit of a confusing feature, but `cache=false` specifically is to disable the "image artifact" cache, while `useOriginal=true` is to bypass the "optimized original" and use the actual original. The method to the madness and why they're treated with different querystring params is that while `cache` is typically only disable in non-prod environments (which is also why it's a disabled feature if `NODE_ENV=production`), while there are some real-world reasons to force usage of the original in production, despite the added slowness. It's an especially handy feature for downloads where you want the highest quality possible (ala `?useOriginal=true&download=true`).

**Comment by asilvas** [comment]
Closing but let me know if further Q's.

**Comment by endymonium** [comment]
Thanks for the quick response! `?useOriginal=true&cache=false` did the trick.

By "disabled in production" you mean that the `cache=false` flag is ignored? Just using `?useOriginal=true` or `?useOriginal=true&download=true` did not work for me.

**Comment by asilvas** [comment]
Correct `cache=false` will be ignored if `NODE_ENV=production` unless you explicitly allow it via `router: { canDisableCache: true }`. Good point about requiring both options, forgot about that nuance.

**Comment by endymonium** [comment]
Cool thanks that solution works for me.

`canDisableCache` and `download=true` seem not to be documented on the main page though :)

**Comment by asilvas** [comment]
@endymonium PR's welcome ;-)
