### ISSUE TITLE
GIF is not working.

### ISSUE THREAD

**Issue by linearloopdevops** [asilvas/node-image-steam#89]
Hello,

https://staging-cdn.ledstripkoning.nl/uploads/tx_multishop/images/products/original/2-m/2-meter-rgb-led-strip-complete-set-120-leds.gif

Can anyone guide how can we enable gif using node-image-stream?

**Comment by asilvas** [comment]
The source you linked is in `webp` format, so I'm guessing you're asking about gif support for output format? If you update to `0.64.0` you can use `fm=f:gif` in querystring.

**Comment by linearloopdevops** [comment]
Thanks @asilvas , Is it necessary to pass `fm=f:gif` ? can we bypass this query string?

**Comment by asilvas** [comment]
isteam's default behaviors are optimized for quality and performance, neither of which `gif` is good for. So yes it is necessary to pass the querystring to override this behavior.

**Comment by asilvas-godaddy** [comment]
Please confirm that it doesn't work without changes to routing (namely changing the `pathDelimiter`). Querystring has been reserved for non-routing options so verifying your config isn't breaking things before I investigate the gif issue.

**Comment by asilvas** [comment]
Oh I see what you mean. You didn't want gif support, you wanted animated gif support. This is not currently an option. Happy to take a PR but due to the fact that animated GIF's cannot be processed in real-time, it's not well suited for image-steam.

**Comment by patelmayankce** [comment]
Can we bypass and directly use an original image without the image-stream process? Is there any option to pass in query string

**Comment by asilvas** [comment]
Happy to take a PR to enable [animated images](https://sharp.pixelplumbing.com/api-output#gif) via querystring. In the mean time, I'm not sure if it satisfies your needs, but you can forcefully enable animations for all images by updating config:

```
processor: {
  sharp: {
    defaults: { animated: true }
  }
}
```

**Comment by linearloopdevops** [comment]
Hello @asilvas 
As per your suggested above configurations, GIF animation working fine, But the GIF Image ratio changed. 
let me give you two URLs below:

Original Image: https://staging-backend-ledstripkoning.ledkoning.nl/uploads/tx_multishop/images/products/original/2-m/2-meter-rgb-led-strip-complete-set-120-leds.gif

Converted Image: https://staging-cdn.ledstripkoning.nl/uploads/tx_multishop/images/products/original/2-m/2-meter-rgb-led-strip-complete-set-120-leds.gif 

Can you please check on this? why image ratio on animated GIF Images?

**Comment by asilvas** [comment]
`0.64.1` published which appears to resolve.

**Comment by linearloopdevops** [comment]
Hello @asilvas 

I upgrade the version and it's working fine.

Thanks a lot.
