### ISSUE TITLE
Error: VipsJpeg: Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by linearloopdevops** [asilvas/node-image-steam#91]
Getting Errors when I convert a JPEG image

Attached Image not converted with below configuration
 
![20210215-221810](https://user-images.githubusercontent.com/96589983/200479675-5bf3565e-6af1-4c30-9380-d2d646479d12.jpeg)

Configurations:
`
sharp: {
        defaults: { animated: true },
        cache: false,
      },
`

Can you please provide a solution to why it's happening?

**Comment by asilvas-godaddy** [comment]
It's an invalid JPEG. 

But you can work around it by updating your config if you want to support these invalid images. https://github.com/lovell/sharp/issues/1578

```
sharp: { defaults: { animated: true, failOnError: false }, cache: false, },
```
